### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by kikolobo** [olback/h7-bootloader-rev#7]
I am trying to do my own board using the H7 chip used in Portenta. I also used the same power manager and used all the same peripherals. However I can't seem to be able to program the boot loader into the chip using the programmer. 

I can upload firmware using Arduino IDE with Portenta board configured using a programmer but the code does not run. My guess is that there is a jump at the boot loader to an address or a fuse bit missing.

Can you provide any clue on how to get code running using the Portenta Arduino core using a programmer?

**Comment by olback** [comment]
A few things to check

* `BOOT0`-pin
* BOOTSEL-pin
* Fuse bits. Which core is starting?
* Try resetting the board after a upload.

If you're using a ST-Link (a real one) you can download STM32 Cube Programmer to set fuse bits. Another options is to use a debugger compatible with openocd like I do [here](https://github.com/olback/h7/blob/1f21f96cd58ed71c8e781cf11069f84b59b73f54/arduino_bootloader/flash-bootloader.sh).

This issue seems to be a bit outside the scope of this repo, I'm trying to reverse engineer the Arduino bootloader, not support third-party boards.

**Comment by olback** [comment]
The bootloader expects usercode to start at `0x08040000`. If you're using the Arduino IDE, this is already taken care of.

**Comment by olback** [comment]
This is how i set the fuse bits:
https://github.com/olback/h7/blob/1f21f96cd58ed71c8e781cf11069f84b59b73f54/arduino_bootloader/flash-bootloader.sh#L25
